### PR TITLE
Define usage pattern of Migration Tool

### PR DESCRIPTION
**Pull request by KrishnaIyer**
#### Summary

This PR updates the `Readme.md` with the target usage of this tool. This can be considered as a mini-design doc. Refs; https://github.com/TheThingsNetwork/lorawan-stack-migrate/pull/40#issuecomment-958721800

There are many different ways of making this tool work. Let's agree upon how this tool is intended to work and then I can implement that.

#### Changes

1. Use only `devices` command to migrate devices. 
 - The first arg will always be the application.
 - The second arg provides multiple ways of choosing how many devices to migrate.
2. Chirpstack has an additional `applications` command that can migrate multiple apps, since that's supported by Chirpstack.

#### Testing

NA

##### Regressions

NA

#### Notes for Reviewers

1. This fixes inconsistencies with `device`/`devices`, `application`/`applications` usage. We will alias them to prevent issues. 
2. This removes the `applications` option for devices in TTNv2 for reasons explained.
3. Whatever way we decide to implement this, I think this deserves a major bump.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.

### CODE REVIEW

**Comment by htdvisser** [comment]
I don't really see why we would change the way this tool works only 4 weeks before V2 shuts down.

The only think the referred issue is asking to fix is the confusing `TTNV2_APP_ID`, why not just focus on that?

**Comment by KrishnaIyer** [comment]
> I don't really see why we would change the way this tool works only 4 weeks before V2 shuts down.

That's what I thought when I made https://github.com/TheThingsNetwork/lorawan-stack-migrate/pull/40

But this tool is also used by our customers for their migration. Also with other NSes (ex: Chirpstack).

**Comment by htdvisser** [comment]
Okay, yeah, then I'm fine with this.

**Comment by KrishnaIyer** [comment]
Great. Could you please check the proposal and approve the PR if that works? I can merge this and then start the implementation.

**Review by htdvisser — APPROVED** [review]

**Pull request merged**
